// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkaqjeofgzqcuudvgdgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrYXFqZW9mZ3pxY3V1ZHZnZGdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzA5ODUsImV4cCI6MjA3MDA0Njk4NX0.wdK5dS8MytGIjf9UihrYkqWMYGdJcPaMfmE5NlittTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});